-- Add this in qb-core/shard.lua

	['weed'] 					 	 = {['name'] = 'weed',				    		['label'] = 'Cannabis',					['weight'] = 100,			['type'] = 'item',		['image'] = 'weed.png',				['unique'] = false,		['useable'] = false,	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = ''},
	['zip_baggie'] 				 	 = {['name'] = 'zip_baggie',				    ['label'] = 'Ziploc Bag',				['weight'] = 10,			['type'] = 'item',		['image'] = 'zip_baggie.png',		['unique'] = false,		['useable'] = false,	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = ''},
	['weed_baggie'] 				 = {['name'] = 'weed_baggie',				    ['label'] = 'Weed Baggie',				['weight'] = 310,			['type'] = 'item',		['image'] = 'weed_baggie.png',		['unique'] = false,		['useable'] = false,	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = ''},
	['chemicals'] 					 = {['name'] = 'chemicals',				    	['label'] = 'Chemicals',				['weight'] = 100,			['type'] = 'item',		['image'] = 'chemicals.png',		['unique'] = false,		['useable'] = false,	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = ''},
	['plastic_baggie'] 				 = {['name'] = 'plastic_baggie',				['label'] = 'Plasic Bag',				['weight'] = 10,			['type'] = 'item',		['image'] = 'plastic_baggie.png',	['unique'] = false,		['useable'] = false,	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = ''},
	['meth'] 						 = {['name'] = 'meth',							['label'] = 'Meth Baggie',				['weight'] = 210,			['type'] = 'item',		['image'] = 'meth_baggy.png',		['unique'] = false,		['useable'] = false,	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = ''},
	['cocaleaf'] 					 = {['name'] = 'cocaleaf',						['label'] = 'Coca Leaf',				['weight'] = 100,			['type'] = 'item',		['image'] = 'cocaleaf.png',			['unique'] = false,		['useable'] = false,	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = ''},
	['cocaine'] 					 = {['name'] = 'cocaine',						['label'] = 'Cocaine Bag',				['weight'] = 210,			['type'] = 'item',		['image'] = 'cocaine_baggy.png',	['unique'] = false,		['useable'] = false,	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = ''},